### PR TITLE
add cython dep

### PR DESCRIPTION
**Pull request by hadim**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/optuna-feedstock/issues/23

### CODE REVIEW

**Comment by hadim** [comment]
@conda-forge-admin please rerender

**Comment by hadim** [comment]
Note that I have added a python selector for `cython` so the feedstock must be **not**no arch. I can also remove the python selector to go back to a noarch package.

**Comment by jakirkham** [comment]
Added a fixes note to the OP linked back to the issue. Hope that is ok 🙂

**Comment by hadim** [comment]
Thanks for linking the issue @jakirkham (I just forgot).

**Comment by jakirkham** [comment]
No worries 🙂

**Pull request closed without merging**
